# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.8.0
    hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional', 'conventional-changelog-conventionalcommits']
      language_version: system
-   repo: https://gitlab.com/jvenom/elixir-pre-commit-hooks
    rev: v1.2.0 # replace with the version you want to use
    hooks: # specify the hooks you want to use here
      - id: mix-format
      - id: mix-test
-   repo: https://github.com/elixirlearners/pre-commit-hooks.git
    rev: c13b915408a40ec30ec811a4eb6cb807dfd2b01a # replace with the version you want to use
    hooks: # specify the hooks you want to use here
      - id: mix-coveralls
      - id: mix-credo
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
    - id: markdownlint
      language_version: system
# -   repo: https://github.com/executablebooks/mdformat.git
#     rev: 0.7.17 # replace with the version you want to use
#     hooks: # specify the hooks you want to use here
#       - id: mdformat
#         language_version: system
